// FeatureBot: turns user stories into runnable Gherkin feature files.
//
// For each story it:
//   1. reads the story (markdown with acceptance criteria),
//   2. collects the step phrases that already have code (the [Given]/[When]/[Then] attributes),
//   3. asks Claude to write a feature file using ONLY those steps,
//   4. checks every step in the result against the real step definitions,
//   5. saves the feature file, and with --run, runs the tests.
//
// It works for any Reqnroll project: settings live in featurebot.json at the repository root.
//
// Usage (from anywhere inside the repository, or F5 in Visual Studio):
//   dotnet run --project FeatureBot                                  -> every story in the stories folder
//   dotnet run --project FeatureBot -- stories/US-002-fhir-patient-api.md
//   dotnet run --project FeatureBot -- stories --run

using System.Diagnostics;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

// ---------------------------------------------------------------------------
// 1. Find the repository and its settings
// ---------------------------------------------------------------------------
var root = FindRepositoryRoot();
if (root is null)
{
    Console.Error.WriteLine("Can't find featurebot.json. Run the bot from inside the test repository.");
    return 1;
}

var config = JsonSerializer.Deserialize<BotConfig>(
    File.ReadAllText(Path.Combine(root, "featurebot.json")),
    new JsonSerializerOptions { PropertyNameCaseInsensitive = true })!;

var stepDefinitionsDir = Path.Combine(root, config.TestProjectDir, "StepDefinitions");
var featuresDir = Path.Combine(root, config.TestProjectDir, "Features");
var runTests = args.Contains("--run");

// Which stories? A file, a folder, or (by default) the whole stories folder.
var target = args.FirstOrDefault(a => !a.StartsWith("--")) ?? config.StoriesDir;
var targetPath = ResolvePath(target, root);
var stories = Directory.Exists(targetPath)
    ? Directory.GetFiles(targetPath, "*.md").OrderBy(f => f).ToList()
    : File.Exists(targetPath) ? new List<string> { targetPath } : new List<string>();

if (stories.Count == 0)
{
    Console.Error.WriteLine($"No stories found at '{target}'.");
    return 1;
}

// ---------------------------------------------------------------------------
// 2. Collect the steps we already have code for
// ---------------------------------------------------------------------------
var steps = FindStepDefinitions(stepDefinitionsDir);
Console.WriteLine($"Project: {config.AppName} ({root})");
Console.WriteLine($"Steps:   {steps.Count} step definitions found");
Console.WriteLine($"Stories: {stories.Count}\n");

var apiKey = Environment.GetEnvironmentVariable("ANTHROPIC_API_KEY");
if (string.IsNullOrWhiteSpace(apiKey))
{
    Console.Error.WriteLine("Set the ANTHROPIC_API_KEY environment variable first.");
    return 1;
}
var model = Environment.GetEnvironmentVariable("CLAUDE_MODEL") ?? "claude-sonnet-5-5";

// ---------------------------------------------------------------------------
// 3-4. Generate and check a feature file for each story
// ---------------------------------------------------------------------------
var allMissing = new List<string>();
Directory.CreateDirectory(featuresDir);

foreach (var storyPath in stories)
{
    var storyName = Path.GetFileNameWithoutExtension(storyPath);   // e.g. US-002-fhir-patient-api
    var storyId = Regex.Match(storyName, @"^[A-Za-z]+-\d+").Value;   // e.g. US-002
    var story = await File.ReadAllTextAsync(storyPath);

    Console.WriteLine($"[{storyName}] asking {model}...");
    string feature;
    try
    {
        feature = CleanUp(await AskClaudeAsync(apiKey, model, BuildSystemPrompt(config, storyId, storyName), BuildUserPrompt(steps, story)));
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine($"[{storyName}] the Claude API call failed: {ex.Message}");
        return 1;
    }

    if (!feature.Contains("Feature:") || !feature.Contains("Scenario"))
    {
        Console.Error.WriteLine($"[{storyName}] Claude's reply doesn't look like a feature file:\n{feature}");
        return 1;
    }

    var featurePath = Path.Combine(featuresDir, $"{storyName}.feature");
    var relativeStory = Path.GetRelativePath(root, storyPath).Replace('\\', '/');
    var header = $"# Generated by FeatureBot from {relativeStory} on {DateTime.Now:yyyy-MM-dd}. Review before committing.\n";
    await File.WriteAllTextAsync(featurePath, header + feature + "\n");
    Console.WriteLine($"[{storyName}] saved {Path.GetRelativePath(root, featurePath)}");

    foreach (var todo in feature.Split('\n').Where(l => l.TrimStart().StartsWith("# TODO")))
    {
        Console.WriteLine($"[{storyName}] Claude flagged: {todo.Trim()}");
    }

    var missing = FindMissingSteps(feature, steps);
    missing.ForEach(m => Console.WriteLine($"[{storyName}] no step definition for: {m}"));
    allMissing.AddRange(missing);
    Console.WriteLine();
}

if (allMissing.Count > 0)
{
    Console.WriteLine("Some steps have no step definition yet. Add them to a class in StepDefinitions, then run the bot again.");
    Console.WriteLine("Not running the tests until every step has a definition.");
    return 2;
}

// ---------------------------------------------------------------------------
// 5. Optionally run the tests
// ---------------------------------------------------------------------------
var testProject = Path.Combine(root, config.TestProjectDir);
if (!runTests)
{
    Console.WriteLine($"All steps match existing definitions. Run the tests in Test Explorer, or: dotnet test {config.TestProjectDir}");
    return 0;
}

Console.WriteLine("Running the tests...\n");
var testRun = Process.Start(new ProcessStartInfo("dotnet")
{
    ArgumentList = { "test", testProject, "--logger", "console;verbosity=normal" },
    WorkingDirectory = root,
    UseShellExecute = false
})!;
await testRun.WaitForExitAsync();

Console.WriteLine($"\nVideos:      {config.TestProjectDir}/bin/Debug/net8.0/artifacts/videos");
Console.WriteLine($"Screenshots: {config.TestProjectDir}/bin/Debug/net8.0/artifacts/screenshots");
return testRun.ExitCode;


// ===========================================================================
// Helper functions
// ===========================================================================

// Walks up from the current folder, then from the bot's own folder, looking for featurebot.json.
// (The second search is what makes F5 in Visual Studio work without setting a working directory.)
static string? FindRepositoryRoot()
{
    foreach (var start in new[] { Directory.GetCurrentDirectory(), AppContext.BaseDirectory })
    {
        for (var dir = new DirectoryInfo(start); dir is not null; dir = dir.Parent)
        {
            if (File.Exists(Path.Combine(dir.FullName, "featurebot.json")))
            {
                return dir.FullName;
            }
        }
    }
    return null;
}

static string ResolvePath(string path, string root) =>
    Path.IsPathRooted(path) ? path
    : File.Exists(path) || Directory.Exists(path) ? Path.GetFullPath(path)
    : Path.Combine(root, path);

// Reads [Given("...")], [When("...")] and [Then("...")] attributes from the step definition files.
static List<StepDefinition> FindStepDefinitions(string folder)
{
    var attribute = new Regex(@"\[(Given|When|Then)\(""((?:[^""\\]|\\.)*)""\)\]");
    return Directory.GetFiles(folder, "*.cs", SearchOption.AllDirectories)
        .SelectMany(file => attribute.Matches(File.ReadAllText(file)))
        .Select(m => new StepDefinition(m.Groups[1].Value, m.Groups[2].Value))
        .DistinctBy(s => (s.Keyword, s.Phrase))
        .ToList();
}

static string BuildSystemPrompt(BotConfig config, string storyId, string storyName) => $"""
    You are a senior QA engineer writing BDD tests for {config.AppName}.
    {config.AppDescription}

    Turn the user story into one Gherkin feature file for Reqnroll.

    Rules:
    - Tag the feature with @{(storyId.Length > 0 ? storyId : storyName)} plus every tag on the story's "Tags:" line.
    - Use the story title as the Feature name and copy the "As a / I want / so that" lines as its description.
    - Cover every acceptance criterion with at least one scenario.
    - When scenarios differ only in their data, use one Scenario Outline with an Examples table.
    - Put steps that every scenario starts with in a Background.
    - Use ONLY the steps listed under AVAILABLE STEPS, word for word, with the keyword shown
      (Given, When or Then). "And" and "But" continue the keyword of the line before.
      Replace {"{string}"} with a value in double quotes and {"{int}"} with a whole number.
    - If a criterion can't be tested with the available steps, don't invent a step.
      Add a comment line starting with "# TODO:" describing the step that is missing.
    - Use synthetic test data only, never real patient or personal data.
    - Reply with the feature file only: no explanation and no markdown code fences.
    """;

static string BuildUserPrompt(List<StepDefinition> steps, string story) => $"""
    AVAILABLE STEPS:
    {string.Join("\n", steps.Select(s => $"- {s.Keyword} {s.Phrase}"))}

    USER STORY:
    {story}
    """;

// Sends one message to the Claude Messages API and returns the text of the reply.
static async Task<string> AskClaudeAsync(string apiKey, string model, string system, string prompt)
{
    using var http = new HttpClient { Timeout = TimeSpan.FromMinutes(2) };
    using var request = new HttpRequestMessage(HttpMethod.Post, "https://api.anthropic.com/v1/messages");
    request.Headers.Add("x-api-key", apiKey);
    request.Headers.Add("anthropic-version", "2023-06-01");

    var body = new
    {
        model,
        max_tokens = 4000,
        system,
        messages = new[] { new { role = "user", content = prompt } }
    };
    request.Content = new StringContent(JsonSerializer.Serialize(body), Encoding.UTF8, "application/json");

    using var response = await http.SendAsync(request);
    var json = await response.Content.ReadAsStringAsync();
    if (!response.IsSuccessStatusCode)
    {
        throw new HttpRequestException($"{(int)response.StatusCode} {response.ReasonPhrase}: {json}");
    }

    using var doc = JsonDocument.Parse(json);
    var text = new StringBuilder();
    foreach (var block in doc.RootElement.GetProperty("content").EnumerateArray())
    {
        if (block.GetProperty("type").GetString() == "text")
        {
            text.Append(block.GetProperty("text").GetString());
        }
    }
    return text.ToString();
}

// Removes markdown fences in case the model adds them anyway.
static string CleanUp(string reply) =>
    string.Join("\n", reply.Replace("\r\n", "\n").Split('\n').Where(l => !l.TrimStart().StartsWith("```"))).Trim();

// Returns every step line that has no matching definition for its keyword.
// "And"/"But" take the keyword of the line before, just like Reqnroll does.
static List<string> FindMissingSteps(string feature, List<StepDefinition> definitions)
{
    var stepLine = new Regex(@"^\s*(Given|When|Then|And|But)\s+(.*?)\s*$");
    var blockStart = new Regex(@"^\s*(Background|Scenario|Scenario Outline|Scenario Template|Example|Rule)\s*:");
    var missing = new List<string>();
    string? keyword = null;

    foreach (var line in feature.Split('\n'))
    {
        if (blockStart.IsMatch(line))
        {
            keyword = null;
            continue;
        }

        var match = stepLine.Match(line);
        if (!match.Success)
        {
            continue;
        }

        var word = match.Groups[1].Value;
        keyword = word is "And" or "But" ? keyword : word;
        var text = match.Groups[2].Value;

        if (keyword is null || !definitions.Any(d => d.Keyword == keyword && d.Pattern.IsMatch(text)))
        {
            missing.Add($"{keyword ?? word} {text}");
        }
    }
    return missing.Distinct().ToList();
}

record BotConfig(string AppName, string AppDescription, string TestProjectDir, string StoriesDir);

record StepDefinition(string Keyword, string Phrase)
{
    // Turns a Cucumber expression like:  I log in with username {string} and password {string}
    // into a regex that matches:          I log in with username "admin" and password "Admin123"
    public Regex Pattern { get; } = new("^" + Regex.Escape(Phrase)
        .Replace(@"\{string}", "\"[^\"]*\"")
        .Replace(@"\{int}", @"-?\d+")
        .Replace(@"\{float}", @"-?\d*\.?\d+")
        .Replace(@"\{word}", @"\S+") + "$");
}
